### ISSUE TITLE
Extension missing Subprimer ID Field and Comment Field Status

### ISSUE THREAD

**Issue by trinberg** [edgi-govdata-archiving/eot-nomination-tool#42] opened 2017-02-01 16:11 UTC
@titaniumbones @sonalranjit @dcwalk - Hi All. The extension works nicely - I just tested the new checkboxes. Thanks so much for your swift work!

I see two quite important changes that need to be made, though:
- The "Subprimer ID" field was removed and we definitely want to be able to record it. Can you ADD a text entry field for Subprimer ID as before, with the associated text "Sub-Primer Num" on the same row in the UI as the other Agency Office Code fields
- Seems like the "Comment" field is required now and the extension will not submit unless it's filled in . Can you make that an OPTIONAL field.

And is there any chance that can get done before 430? Thanks so much.

**Comment by sonalranjit** [comment] 2017-02-01 16:16
working on it

**Comment by titaniumbones** [comment] 2017-02-01 16:19
thx sonalr, sorry about the error, I thought I'd confirmed the
subprimer, must have been tired.

**Comment by sonalranjit** [comment] 2017-02-01 16:33
Updated it, ran few test submissions, seems to be working. Please conform and merge #43 
@titaniumbones @trinberg

**Comment by trinberg** [comment] 2017-02-01 16:45
@sonalranjit - can the subprimer field be on the same row as the agency office code? And the checkboxes be all on their own row as well? It seems like there's enough room now that it's wider. The UI looks jumbled as it is now.

**Comment by titaniumbones** [comment] 2017-02-01 16:48
it's a bit annoying, I can futz w/ it if you want @sonalranjit or if you
try I think the trick wd be to keep the label for subprimer higher than
the agency id inputs, and float it right. Inputs would need to be
cleared obvs.

**Comment by titaniumbones** [comment] 2017-02-01 16:53
(let me know if you want me to do it, or if you have time in the next couple of hours).

**Comment by sonalranjit** [comment] 2017-02-01 16:54
on it

**Comment by sonalranjit** [comment] 2017-02-01 17:33
taking a bit long than anticipated, have to get back to work, I duno if you can handle this one @titaniumbones

**Comment by titaniumbones** [comment] 2017-02-01 18:23
fixed, pushed, merged, upversioned.

**Closed as completed by titaniumbones** 2017-02-01 18:23 UTC

**Comment by trinberg** [comment] 2017-02-01 18:33
awesome - thanks! will get back to you with feedback after the event
